routes/web.php
<?php

use Illuminate\Support\Facades\Route;

$this->settingRole = config("settings.role");

Route::group([
    "namespace" => "Home",
    "as" => "home.",
], function () {
    Route::group([
        "namespace" => "Dashboards"
    ], function () {
        Route::resource("dashboards", "DashboardController")->only(["index"]);
        Route::group([
            "as" => "dashboards.",
        ], function () {
            Route::get("index", "DashboardController@index")->name("index");
            Route::get("", "DashboardController@index")->name("index");
        });
    });

    Route::group([
        "namespace" => "Histories"
    ], function () {
        Route::resource("histories", "HistoryController")->only(["index"]);
    });

    Route::group([
        "namespace" => "Usabilities"
    ], function () {
        Route::resource("usabilities", "UsabilityController")->only(["index", "show"]);
    });

    Route::group([
        "namespace" => "Items"
    ], function () {
        Route::resource("items", "ItemController")->only(["index", "show"]);
    });

    Route::group([
        "namespace" => "Searches"
    ], function () {
        // Route::resource("searches", "SearchController")->only(["index"]);
        Route::post("searches", "SearchController@index")->name("searches.index");
    });
});

Route::namespace("Auth")->group(function () {
    // Route::get("", "LoginController@showLoginForm")->name("home.dashboards.index");
    Route::get("login", 'LoginController@showLoginForm')->name("login");
    Route::post("login", 'LoginController@login')->name("login");
    Route::post("logout", 'LoginController@logout')->name("logout");
});

Route::middleware(["auth"])->group(function () {
    //Administrator
    Route::group([
        "middleware" => ["role:" . implode("|", $this->settingRole["administrator"])],
        "namespace" => "Administrator",
        "as" => "administrator.",
        "prefix" => "administrator"
    ], function () {
        Route::group([
            "namespace" => "Dashboards",
        ], function () {
            Route::resource("dashboards", "DashboardController")->only(["index"]);
            Route::group([
                "as" => "dashboards.",
            ], function () {
                Route::get("", "DashboardController@index")->name("index");
            });
        });

        Route::group([
            "namespace" => "Profiles",
            "as" => "profile.",
            "prefix" => "profile"
        ], function () {
            Route::get("index", "ProfileController@index")->name("index");
            Route::get("", "ProfileController@index")->name("index");
            Route::put("", "ProfileController@update")->name("update");
            Route::delete("", "ProfileController@destroy")->name("destroy");
            Route::put("password", "ProfileController@updatePassword")->name("update-password");
            Route::put("avatar", "ProfileController@updateAvatar")->name("update-avatar");
        });

        Route::group([
            "middleware" => ["role:" . $this->settingRole["administrator"]["superadmin"]],
        ], function () {
            Route::group([
                "namespace" => "Roles"
            ], function () {
                Route::resource("roles", "RoleController")->except(["show"]);
            });

            Route::group([
                "namespace" => "Permissions"
            ], function () {
                Route::resource("permissions", "PermissionController")->except(["show", "create", "edit"]);
            });
        });

        Route::group([
            "namespace" => "Users"
        ], function () {
            Route::resource("users", "UserController")->except(["show"]);
            Route::group([
                "as" => "users.",
                "prefix" => "users"
            ], function () {
                Route::put("{id}/password", "UserController@updatePassword")->name("update-password");
                Route::put("{id}/status", "UserController@updateStatus")->name("update-status");
                Route::put("{id}/avatar", "UserController@updateAvatar")->name("update-avatar");

                Route::group([
                    "as" => "deleted.",
                    "prefix" => "deleted"
                ], function () {
                    Route::get("index", "UserDeletedController@index")->name("index");
                    Route::get("", "UserDeletedController@index")->name("index");
                    Route::post("{id}/restore", "UserDeletedController@restore")->name("restore");
                });
            });
        });

        Route::group([
            "namespace" => "Usabilities"
        ], function () {
            Route::resource("usabilities", "UsabilityController")->except(["show"]);
        });

        Route::group([
            "namespace" => "Items"
        ], function () {
            Route::resource("items", "ItemController")->except(["show"]);
        });

        Route::group([
            "namespace" => "Settings",
            "as" => "settings.",
            "prefix" => "settings"
        ], function () {
            Route::resource("dashboards", "DashboardController")->only(["index", "store"]);
            Route::resource("histories", "HistoryController")->only(["index", "store"]);
        });
    });
});

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Spatie\Permission\Traits\HasRoles;

use Tymon\JWTAuth\Contracts\JWTSubject;

class User extends Authenticatable implements JWTSubject
{
    use Notifiable;
    use HasRoles;

    protected $fillable = [
        "person_id",
        "username",
        "email",
        "password",
        "is_active"
    ];

    protected $hidden = [
        "password",
        "remember_token",
    ];

    protected $casts = [
        "email_verified_at" => "datetime",
    ];

    public function person()
    {
        return $this->belongsTo(Models\Person::class);
    }

    public function getJWTIdentifier()
    {
        return $this->getKey();
    }

    public function getJWTCustomClaims()
    {
        return [];
    }
}

app/Http/Controllers/Administrator/Users/UserController.php
<?php

namespace App\Http\Controllers\Administrator\Users;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

use Spatie\Permission\Models\Role;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Storage;

use App\User;
use App\Models\Person;

class UserController extends Controller
{
    public function __construct()
    {
        $this->settingRole = config("settings.role");

        $this->middleware(function ($request, $next) {
            $this->authUser = auth()->user();
            return $next($request);
        });
    }

    public function index()
    {
        if (request()->ajax()) {
            if ($this->authUser->hasRole($this->settingRole["administrator"]["superadmin"])) {
                $people = Person::orderBy("full_name")->whereHas("user")->get();
            } else {
                $people = Person::orderBy("full_name")->whereHas("user.roles", function ($roles) {
                    $roles->where("name", "!=", $this->settingRole["administrator"]["superadmin"]);
                })->get();
            }

            return datatables()->of($people)
                ->addColumn("column_name", function ($data) {
                    return '
                    <img class="rounded-circle mr-2 float-left" src="' . url($data->avatar ?? '/assets/images/avatar.png') . '" style="height: 2.7rem;" />
                    <div class="float-left">
                        ' . $data->full_name . '
                        <small class="d-flex mt-1">' . $data->user->username ?? $data->user->email  . '</small>
                    </div>
                    ';
                })
                ->addColumn("column_roles", function ($data) {
                    $roles = '';
                    if ($data->user->roles->count()) {
                        foreach ($data->user->roles->sortBy('name') as $role) {
                            $roles .= '<small class="btn btn-sm btn-pill btn-warning p-1 pr-3 pl-3 m-1">' . $role->name . '</small>';
                        }
                    } else {
                        $roles = '<small class="font-italic m-1">Role Not Found</small>';
                    }

                    return $roles;
                })
                ->addColumn("column_is_active", function ($data) {
                    return '
                    <div class="custom-control custom-toggle custom-toggle">
                        <input type="checkbox" id="set-is-active[' . $data->id . ']" class="custom-control-input toggle-status" ' . ($data->user->is_active ? "checked" : "") . '>
                        <label class="custom-control-label" for="set-is-active[' . $data->id . ']"></label>
                    </div>
                    ';
                })
                ->addColumn("column_actions", function ($data) {
                    return '
                    <div class="row m-0">
                        <div class="col mr-1 ml-1 p-0">
                            <a href="' . route('administrator.users.edit', $data->id) . '"  class="btn btn-sm btn-info col-sm-12">
                                <i class="fas fa-pencil-alt mr-1"></i>
                                Edit
                            </a>
                        </div>
                        <div class="col mr-1 ml-1 p-0">
                            <button type="button" class="btn btn-sm btn-danger col-sm-12" onclick="handleDestroy(' . $data->id . ')">
                                <i class="fas fa-trash-alt mr-1"></i>
                                Hapus
                            </button>
                        </div>
                    </div>
                    ';
                })
                ->addIndexColumn()
                ->escapeColumns([])
                ->make(true);
        }

        return view(
            "administrator.users.index"
        );
    }

    public function create()
    {
        if ($this->authUser->hasRole($this->settingRole["administrator"]["superadmin"])) {
            $roles = Role::orderBy("name")->pluck("name", "id")->all();
        } else {
            $roles = Role::orderBy("name")->where("name", "!=", $this->settingRole["administrator"]["superadmin"])->pluck("name", "id")->all();
        }

        return view(
            "administrator.users.create",
            compact("roles")
        );
    }

    public function store(Request $request)
    {
        $this->validate($request, [
            "name" => "required|string|max:255",
            "email" => "required|email|max:255|unique:users",
            // "username" => "required|string|max:255|unique:users",
            "password" => "required|string|min:6|confirmed"
        ]);

        if ($this->authUser->hasRole($this->settingRole["administrator"])) {
            $this->validate($request, [
                "role" => "required"
            ]);
        }

        $person = Person::updateOrCreate(
            [
                "full_name" => $request->input("name")
            ]
        );

        $user = User::updateOrCreate(
            [
                "person_id" => $person->id
            ],
            [
                "username" => $request->username,
                "password" => Hash::make($request->password),
                "email" => $request->email ?? NULL
            ]
        );

        if ($this->authUser->hasRole($this->settingRole["administrator"])) {
            $user->assignRole($request->role);
        }

        return redirect()->route(
            "administrator.users.index"
        )->with("success", "User berhasil ditambahkan.");
    }

    public function edit($id)
    {
        $person = Person::find($id);

        if ($this->authUser->hasRole($this->settingRole["administrator"]["superadmin"])) {
            $roles = Role::orderBy("name")->pluck("name", "id")->all();
        } else {
            $roles = Role::orderBy("name")->where("name", "!=", $this->settingRole["administrator"]["superadmin"])->pluck("name", "id")->all();
        }

        return view(
            "administrator.users.edit",
            compact("person", "roles")
        );
    }

    public function update(Request $request, $id)
    {
        $this->validate($request, [
            "name" => "required|string|max:255",
            "email" => "required|email|max:255|unique:users,email," . $id,
            // "username" => "required|string|max:255|unique:users,username," . $id,
        ]);

        if ($this->authUser->hasRole($this->settingRole["administrator"])) {
            $this->validate($request, [
                "role" => "required"
            ]);
        }

        $person = Person::find($id);
        $person->update(
            [
                "full_name" => $request->name
            ]
        );

        $user = User::updateOrCreate(
            [
                "person_id" => $person->id
            ],
            [
                "username" => $request->username ?? $person->user->username,
                "email" => $request->email
            ]
        );

        if ($this->authUser->hasRole($this->settingRole["administrator"])) {
            DB::table("model_has_roles")->where("model_id", $user->id)->delete();
            $user->assignRole($request->role);
        }

        return redirect()->route(
            "administrator.users.edit",
            $id
        )->with("success", "User berhasil diperbarui.");
    }

    public function destroy($id)
    {
        if ($this->authUser->id === (int) $id) {
            Auth::logout();
        }

        $person = Person::find($id);
        $person->user->update(["is_active" => 0]);
        $person->delete();

        return redirect()->route(
            "administrator.users.index"
        )->with("success", "User berhasil dihapus.");
    }

    public function updatePassword(Request $request, $id)
    {
        $request->validate([
            "current_password" => "required",
            "new_password" => "required|same:confirm_new_password",
        ]);

        $person = Person::find($id);
        if (Hash::check($request->current_password, $person->user->password)) {
            $person->user->update(["password" => Hash::make($request->new_password)]);
            return redirect()->back()->with("success", "Password berhasil diperbarui.");
        } else {
            return redirect()->back()->withErrors(["current_password" => "The attribute is match with old password."]);
        }
    }

    public function updateStatus(Request $request, $id)
    {
        $person = Person::find($id);
        $person->user->update(["is_active" => $request->status]);

        if ($this->authUser->id === $person->user->id && $request->status === "0") {
            Auth::logout();
        }

        return response()->json([
            "status" => true,
            "message" => "Status change successfully."
        ]);
    }

    public function updateAvatar(Request $request, $id)
    {
        $request->validate([
            "avatar"        => "required|mimes:jpg,jpeg,png"
        ]);

        if ($request->file("avatar")) {
            $person = Person::find($id);

            $fileName = date("Y_m_d_His") . "_" . uniqid() . "." . $request->file("avatar")->extension();
            $filePath = $request->file("avatar")->storeAs(
                "storage/images/avatars",
                $fileName,
                "public"
            );

            if ($filePath) {
                if (!preg_match("/^(\/)?seeds/i", $person->avatar)) {
                    Storage::disk("public")->delete($person->avatar);
                }

                Person::updateOrCreate(
                    [
                        "id"     => $person->id
                    ],
                    [
                        "avatar"    => $filePath
                    ]
                );

                return redirect()->route(

resources/views/administrator/users/deleted/index.blade.php
@extends('administrator.layouts.template')

@section('css')
<link href="https://cdn.datatables.net/1.10.22/css/dataTables.bootstrap4.min.css" rel="stylesheet">

<style>
    .dataTables_length,
    .dataTables_filter,
    .dataTables_info,
    .dataTables_paginate {
        margin-left: 1.1rem !important;
        margin-right: 1.1rem !important;
    }

    .dataTables_length,
    .dataTables_info {
        text-align: left;
    }
</style>
@endsection

@section('content')
@if ($message = session()->get("success"))
<div class="alert alert-success alert-dismissible fade show mb-0" role="alert">
    <button type="button" class="close h-100" data-dismiss="alert" aria-label="Close" style="outline: none;">
        <span aria-hidden="true">×</span>
    </button>
    <i class="fa fa-check mx-2"></i>
    <strong>{{ $message }}</strong>
</div>
@endif

<div class="main-content-container container-fluid px-4">
    <!-- Page Header -->
    <div class="page-header row no-gutters mb-4"></div>
    <!-- End Page Header -->

    <div class="row">
        <div class="col">
            <div class="card card-small mb-4">
                <div class="card-header border-bottom">
                    <h6 class="float-left m-0 mt-1">Users</h6>
                </div>

                <div class="card-body p-0 pt-3 pb-2 table-responsive">
                    <table id="table" class="table table-hover w-100">
                        <thead class="bg-light">
                            <tr class="text-center">
                                <th scope="col" class="border-0" style="width: 50px;">#</th>
                                <th scope="col" class="border-0">Name</th>
                                <th scope="col" class="border-0">Deleted Time</th>
                                <th scope="col" class="border-0">Role</th>
                                <th scope="col" class="border-0" style="width: 90px; min-width: 90px;">Actions</th>
                            </tr>
                        </thead>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

<div hidden>
    <form id="option-form" method="POST">
        @csrf
        <input type="hidden" id="option-method" name="_method" value="POST">
    </form>
</div>
@endsection

@section('javascript')
<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
<script src="https://cdn.datatables.net/1.10.22/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.22/js/dataTables.bootstrap4.min.js"></script>

<script>
    const handleRestore = id =>
        swal({
            title: "Are you sure?",
            text: "You will reactivate this user",
            icon: "warning",
            buttons: true,
        })
        .then(willRestore => {
            if (willRestore) {
                $("#option-form").attr("action", `{{ route('administrator.users.deleted.index') }}/${id}/restore`);
                $("#option-method").val("POST");
                $("#option-form").submit();
            }
        });

    $("#table").DataTable({
        responsive: true,
        language: {
            paginate: {
                previous: "‹",
                next: "›"
            }
        },
        processing: true,
        serverSide: true,
        ajax: {
            url: "{{ request()->url() }}",
            headers: {
                "X-CSRF-TOKEN": $('meta[name="csrf-token"]').attr('content')
            }
        },
        columns: [{
            data: "DT_RowIndex",
            orderable: false,
            searchable: false
        }, {
            data: "column_name"
        }, {
            data: "column_deleted_at"
        }, {
            data: "column_roles"
        }, {
            data: "column_actions",
            orderable: false,
            searchable: false
        }],
        order: [
            [1, "asc"]
        ],
        createdRow: function(row, data, indice) {
            $('td:eq(0)', row).addClass("align-middle text-center");
            $('td:eq(1)', row).addClass("align-middle d-flex");
            $('td:eq(2)', row).addClass("align-middle text-right");
            $('td:eq(3)', row).addClass("align-middle text-center");
            $('td:eq(4)', row).addClass("align-middle");
        }
    });
</script>
@endsection