routes/web.php
<?php

use Illuminate\Support\Facades\Route;

$this->settingRole = config("settings.role");

Route::group([
    "namespace" => "Home",
    "as" => "home.",
], function () {
    Route::group([
        "namespace" => "Dashboards"
    ], function () {
        Route::resource("dashboards", "DashboardController")->only(["index"]);
        Route::group([
            "as" => "dashboards.",
        ], function () {
            Route::get("index", "DashboardController@index")->name("index");
            Route::get("", "DashboardController@index")->name("index");
        });
    });

    Route::group([
        "namespace" => "Histories"
    ], function () {
        Route::resource("histories", "HistoryController")->only(["index"]);
    });

    Route::group([
        "namespace" => "Usabilities"
    ], function () {
        Route::resource("usabilities", "UsabilityController")->only(["index", "show"]);
    });

    Route::group([
        "namespace" => "Items"
    ], function () {
        Route::resource("items", "ItemController")->only(["index", "show"]);
    });

    Route::group([
        "namespace" => "Searches"
    ], function () {
        // Route::resource("searches", "SearchController")->only(["index"]);
        Route::post("searches", "SearchController@index")->name("searches.index");
    });
});

Route::namespace("Auth")->group(function () {
    // Route::get("", "LoginController@showLoginForm")->name("home.dashboards.index");
    Route::get("login", 'LoginController@showLoginForm')->name("login");
    Route::post("login", 'LoginController@login')->name("login");
    Route::post("logout", 'LoginController@logout')->name("logout");
});

Route::middleware(["auth"])->group(function () {
    //Administrator
    Route::group([
        "middleware" => ["role:" . implode("|", $this->settingRole["administrator"])],
        "namespace" => "Administrator",
        "as" => "administrator.",
        "prefix" => "administrator"
    ], function () {
        Route::group([
            "namespace" => "Dashboards",
        ], function () {
            Route::resource("dashboards", "DashboardController")->only(["index"]);
            Route::group([
                "as" => "dashboards.",
            ], function () {
                Route::get("", "DashboardController@index")->name("index");
            });
        });

        Route::group([
            "namespace" => "Profiles",
            "as" => "profile.",
            "prefix" => "profile"
        ], function () {
            Route::get("index", "ProfileController@index")->name("index");
            Route::get("", "ProfileController@index")->name("index");
            Route::put("", "ProfileController@update")->name("update");
            Route::delete("", "ProfileController@destroy")->name("destroy");
            Route::put("password", "ProfileController@updatePassword")->name("update-password");
            Route::put("avatar", "ProfileController@updateAvatar")->name("update-avatar");
        });

        Route::group([
            "middleware" => ["role:" . $this->settingRole["administrator"]["superadmin"]],
        ], function () {
            Route::group([
                "namespace" => "Roles"
            ], function () {
                Route::resource("roles", "RoleController")->except(["show"]);
            });

            Route::group([
                "namespace" => "Permissions"
            ], function () {
                Route::resource("permissions", "PermissionController")->except(["show", "create", "edit"]);
            });
        });

        Route::group([
            "namespace" => "Users"
        ], function () {
            Route::resource("users", "UserController")->except(["show"]);
            Route::group([
                "as" => "users.",
                "prefix" => "users"
            ], function () {
                Route::put("{id}/password", "UserController@updatePassword")->name("update-password");
                Route::put("{id}/status", "UserController@updateStatus")->name("update-status");
                Route::put("{id}/avatar", "UserController@updateAvatar")->name("update-avatar");

                Route::group([
                    "as" => "deleted.",
                    "prefix" => "deleted"
                ], function () {
                    Route::get("index", "UserDeletedController@index")->name("index");
                    Route::get("", "UserDeletedController@index")->name("index");
                    Route::post("{id}/restore", "UserDeletedController@restore")->name("restore");
                });
            });
        });

        Route::group([
            "namespace" => "Usabilities"
        ], function () {
            Route::resource("usabilities", "UsabilityController")->except(["show"]);
        });

        Route::group([
            "namespace" => "Items"
        ], function () {
            Route::resource("items", "ItemController")->except(["show"]);
        });

        Route::group([
            "namespace" => "Settings",
            "as" => "settings.",
            "prefix" => "settings"
        ], function () {
            Route::resource("dashboards", "DashboardController")->only(["index", "store"]);
            Route::resource("histories", "HistoryController")->only(["index", "store"]);
        });
    });
});

app/Http/Controllers/Administrator/Dashboards/DashboardController.php
<?php

namespace App\Http\Controllers\Administrator\Dashboards;

use App\Http\Controllers\Controller;
use Spatie\Permission\Models\Permission;
use Spatie\Permission\Models\Role;

use App\Models\Person;

class DashboardController extends Controller
{
    public function __construct()
    {
        $this->settingRole = config("settings.role");

        $this->middleware(function ($request, $next) {
            $this->authUser = auth()->user();
            return $next($request);
        });
    }

    public function index()
    {
        return redirect()->route("administrator.settings.dashboards.index");

        if ($this->authUser->hasRole($this->settingRole["administrator"]["superadmin"])) {
            $permissions = Permission::all();
            $roles = Role::all();
            $people = Person::withTrashed()->orderBy("full_name")->whereHas("user");

            $compact = compact("people", "permissions", "roles");
        } else {
            $people = Person::withTrashed()->orderBy("full_name")->whereHas("user.roles", function ($roles) {
                $roles->where("name", "!=", $this->settingRole["administrator"]["superadmin"]);
            });

            $compact = compact("people");
        }

        return view(
            "administrator.dashboards.index",
            $compact
        );
    }
}

app/Http/Controllers/Administrator/Items/ItemController.php
<?php

namespace App\Http\Controllers\Administrator\Items;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;

use App\Models\Item;
use App\Models\ItemImage;
use App\Models\ItemUsability;
use App\Models\Usability;

class ItemController extends Controller
{
    public function __construct()
    {
        $this->settingRole = config("settings.role");

        $this->middleware(function ($request, $next) {
            $this->authUser = auth()->user();
            return $next($request);
        });
    }

    public function index()
    {
        if (request()->ajax()) {
            $items = Item::orderBy("name")->get();
            return datatables()->of($items)
                ->addColumn("column_usabilities", function ($data) {
                    if ($data->usabilities && $data->usabilities->count()) {
                        $usabilities = '';
                        foreach ($data->usabilities->sortBy('name') as $usability) {
                            $usabilities .= '<small class="btn btn-sm btn-pill btn-warning p-1 pr-3 pl-3 m-1">' . $usability->name . '</small>';
                        }
                    } else {
                        $usabilities = '<small class="font-italic m-1">Usability Not Found</small>';
                    }

                    return $usabilities;
                })
                ->addColumn("column_actions", function ($data) {
                    return '
                    <div class="row m-0">
                        <div class="col mr-1 ml-1 p-0">
                            <a href="' . route('administrator.items.edit', $data->id) . '"  class="btn btn-sm btn-info col-sm-12">
                                <i class="fas fa-pencil-alt mr-1"></i>
                                Edit
                            </a>
                        </div>
                        <div class="col mr-1 ml-1 p-0">
                            <button type="button" class="btn btn-sm btn-danger col-sm-12" onclick="handleDestroy(' . $data->id . ')">
                                <i class="fas fa-trash-alt mr-1"></i>
                                Hapus
                            </button>
                        </div>
                    </div>
                    ';
                })
                ->addIndexColumn()
                ->escapeColumns([])
                ->make(true);
        }

        return view(
            "administrator.items.index"
        );
    }

    public function create()
    {
        $usabilities = Usability::orderBy("name")->pluck("name", "id")->all();

        return view(
            "administrator.items.create",
            compact("usabilities")
        );
    }

    public function store(Request $request)
    {
        $this->validate($request, [
            "name" => "required",
            "description" => "required",
            "usability" => "required|array",
            "usability.*" => "required|exists:usabilities,id",
            'image' => 'required',
            'image.*.file' => 'image|mimes:jpg,jpeg,png'
        ]);

        $item = Item::updateOrCreate(
            [
                "name" => $request->name,
                "description" => $request->description
            ]
        );

        if (count($request->usability) > 0) {
            $usabilities = [];
            foreach ($request->usability as $usabilityId) {
                $usability = Usability::find($usabilityId);
                if ($usability) {
                    $usabilities[] = $usability->id;
                }
            }

            $item->usabilities()->sync($usabilities);
        }

        if (count($request->file("image")) > 0) {
            foreach ($request->file("image") as $image) {
                $fileName = date("Y_m_d_His") . "_" . uniqid() . "." . $image["file"]->extension();
                $filePath = $image["file"]->storeAs(
                    "storage/images/items",
                    $fileName,
                    "public"
                );

                if ($filePath) {
                    ItemImage::create([
                        "item_id" => $item->id,
                        "file" => $filePath
                    ]);
                }
            }
        }

        return redirect()->route(
            "administrator.items.index"
        )->with("success", "Jenis kain berhasil ditambahkan.");
    }

    public function edit($id)
    {
        $item = Item::findOrFail($id);
        $usabilities = Usability::orderBy("name")->pluck("name", "id")->all();

        return view(
            "administrator.items.edit",
            compact("item", "usabilities")
        );
    }

    public function update(Request $request, $id)
    {
        $this->validate($request, [
            "name" => "required",
            "description" => "required",
            "usability" => "required|array",
            "usability.*" => "required|exists:usabilities,id",
            'image.*.file' => 'nullable|image|mimes:jpg,jpeg,png'
        ]);

        $item = Item::updateOrCreate(
            [
                "id" => $id
            ],
            [
                "name" => $request->name,
                "description" => $request->description
            ]
        );

        if (count($request->usability) > 0) {
            $usabilities = [];
            foreach ($request->usability as $usabilityId) {
                $usability = Usability::find($usabilityId);
                if ($usability) {
                    $usabilities[] = $usability->id;
                }
            }

            $item->usabilities()->sync($usabilities);
        } else {
            $item->usabilities()->sync([]);
        }

        $toBeDeleted = $item->images()->pluck("id", "id")->toArray();
        $tempImages = @$_FILES["image"]["name"];
        if ($tempImages) {
            foreach ($tempImages as $imageId => $tempImage) {
                if ($request->file("image") && array_key_exists($imageId, $request->file("image"))) {
                    $newImage = $request->file("image")[$imageId];
                    $fileName = date("Y_m_d_His") . "_" . uniqid() . "." . $newImage["file"]->extension();
                    $filePath = $newImage["file"]->storeAs(
                        "storage/images/items",
                        $fileName,
                        "public"
                    );

                    if ($filePath) {
                        $image = ItemImage::find($imageId);
                        if ($image) {
                            if (!preg_match("/^(\/)?seeds/i", $image->file)) {
                                Storage::disk("public")->delete($image->file);
                            }
                        } else {
                            $imageId = NULL;
                        }

                        ItemImage::updateOrCreate(
                            [
                                "id" => $imageId
                            ],
                            [
                                "item_id" => $item->id,
                                "file" => $filePath
                            ]
                        );
                    }
                }

                unset($toBeDeleted[$imageId]);
            }
        }

        if ($toBeDeleted) {
            foreach ($toBeDeleted as $toBeDeletedId) {
                $image = ItemImage::find($toBeDeletedId);
                if ($image && !preg_match("/^(\/)?seeds/i", $image->file)) {
                    Storage::disk("public")->delete($image->file);
                    $image->delete();
                }
            }
        }

        return redirect()->back()->with("success", "Jenis kain berhasil diperbarui.");
    }

    public function destroy($id)
    {
        Item::findOrFail($id)->delete();
        return redirect()->back()->with("success", "Jenis kain berhasil dihapus.");
    }
}

app/Http/Controllers/Administrator/Permissions/PermissionController.php
<?php

namespace App\Http\Controllers\Administrator\Permissions;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

use Spatie\Permission\Models\Permission;

class PermissionController extends Controller
{
    function __construct()
    {
        $this->middleware("permission:permission-list|permission-create|permission-edit|permission-delete", ["only" => ["index", "store"]]);
        $this->middleware("permission:permission-create", ["only" => ["create", "store"]]);
        $this->middleware("permission:permission-edit", ["only" => ["edit", "update"]]);
        $this->middleware("permission:permission-delete", ["only" => ["destroy"]]);
    }

    public function index()
    {
        if (request()->ajax()) {
            $permissions = Permission::orderBy("name")->get();
            return datatables()->of($permissions)
                ->addColumn("column_actions", function ($data) {
                    return '
                    <div class="row m-0">
                        <div class="col mr-1 ml-1 p-0">
                            <button type="button" class="edit btn btn-sm btn-info col-sm-12">
                                <i class="fas fa-pencil-alt mr-1"></i>
                                Edit
                            </button>
                        </div>
                        <div class="col mr-1 ml-1 p-0">
                            <button type="button" class="btn btn-sm btn-danger col-sm-12" onclick="handleDestroy(' . $data->id . ')">
                                <i class="fas fa-trash-alt mr-1"></i>
                                Destroy
                            </button>
                        </div>
                    </div>
                    ';
                })
                ->addIndexColumn()
                ->escapeColumns([])
                ->make(true);
        }

        return view(
            "administrator.permissions.index"
        );
    }

    public function store(Request $request)
    {
        $this->validate($request, [
            "name" => "required|unique:roles,name"
        ]);

        Permission::updateOrCreate(
            [
                "name" => $request->name,
                "guard_name" => "web"
            ],
            []
        );

        return redirect()->back()->with("success", "Permission created successfully.");
    }

    public function update(Request $request, $id)
    {
        $this->validate($request, [
            "name" => "required"
        ]);

        Permission::updateOrCreate(
            [
                "id" => $id
            ],
            [
                "name" => $request->name
            ]
        );

        return redirect()->back()->with("success", "Permission updated successfully.");
    }

    public function destroy($id)
    {
        Permission::findOrFail($id)->delete();
        return redirect()->back()->with("success", "Permission deleted successfully.");
    }
}

resources/views/administrator/usabilities/index.blade.php
@extends('administrator.layouts.template')

@section('css')
<link href="https://cdn.datatables.net/1.10.22/css/dataTables.bootstrap4.min.css" rel="stylesheet">

<style>
    .dataTables_length,
    .dataTables_filter,
    .dataTables_info,
    .dataTables_paginate {
        margin-left: 1.1rem !important;
        margin-right: 1.1rem !important;
    }

    .dataTables_length,
    .dataTables_info {
        text-align: left;
    }
</style>
@endsection

@section('content')
@if ($message = session()->get("success"))
<div class="alert alert-success alert-dismissible fade show mb-0" role="alert">
    <button type="button" class="close h-100" data-dismiss="alert" aria-label="Close" style="outline: none;">
        <span aria-hidden="true">×</span>
    </button>
    <i class="fa fa-check mx-2"></i>
    <strong>{{ $message }}</strong>
</div>
@endif

@if ($errors->all())
<div class="alert alert-danger alert-dismissible fade show mb-0" role="alert">
    <button type="button" class="close h-100" data-dismiss="alert" aria-label="Close" style="outline: none;">
        <span aria-hidden="true">×</span>
    </button>
    <i class="fa fa-info mx-2"></i>
    <strong>{{ $errors->first() }}</strong>
</div>
@endif

<div class="main-content-container container-fluid px-4">
    <!-- Page Header -->
    <div class="page-header row no-gutters mb-4"></div>
    <!-- End Page Header -->

    <div class="row">
        <div class="col">
            <div class="card card-small mb-4">
                <div class="card-header border-bottom">
                    <h6 class="float-left m-0 mt-1">Tipe Ulos</h6>
                    <div class="float-right">
                        <button type="button" class="btn btn-sm btn-success" onclick="handleCreate()">
                            <i class="material-icons">add</i>
                            Tambah
                        </button>
                    </div>
                </div>

                <div class="card-body p-0 pt-3 pb-2 table-responsive">
                    <table id="table" class="table table-hover w-100">
                        <thead class="bg-light">
                            <tr class="text-center">
                                <th scope="col" class="border-0" style="width: 50px;">#</th>
                                <th scope="col" class="border-0">Nama</th>
                                <th scope="col" class="border-0" style="width: 180px; min-width: 180px;">Aksi</th>
                            </tr>
                        </thead>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="option" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <form id="option-form" method="POST">
            @csrf
            <input type="hidden" id="option-method" name="_method" value="POST">

            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="option-title">Option</h5>

                    <button type="button" class="close" data-dismiss="modal" aria-label="Close" style="outline:none;">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>

                <div class="modal-body">
                    <div class="row">
                        <div class="col-sm-12">
                            <div class="form-group">
                                <label for="option-name" class="col-form-label">Nama</label>
                                <input type="text" id="option-name" name="name" class="form-control" placeholder="Nama" value="" required>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="modal-footer">
                    <button type="submit" id="option-save" class="btn btn-primary">
                        <i class="fas fa-save"></i>
                        Simpan
                    </button>
                </div>
            </div>
        </form>
    </div>
</div>
@endsection

@section('javascript')
<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
<script src="https://cdn.datatables.net/1.10.22/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.22/js/dataTables.bootstrap4.min.js"></script>
<script src="http://ajax.aspnetcdn.com/ajax/jquery.validate/1.11.1/jquery.validate.min.js"></script>

<script>
    const handleDestroy = id => {
        swal({
                title: "Apakah Anda yakin?",
                text: "Setelah dihapus, kamu tidak dapat mengembalikan item ini!",
                icon: "warning",
                buttons: true,
                dangerMode: true,
            })
            .then(willDelete => {
                if (willDelete) {
                    $("#option-form").attr("action", `{{ route('administrator.usabilities.index') }}/${id}`);
                    $("#option-method").val("DELETE");
                    $("#option-form").submit();
                }
            });
    }

    const handleCreate = () => {
        $("#option-form").attr("action", `{{ route('administrator.usabilities.store') }}`);
        $("#option-method").val('POST');
        $("#option-title").html("Tambah Tipe Ulos");

        $("#option-name").val("");

        $("#option").modal("show");
    }

    $(document).on("click", ".edit", function() {
        const tr = $(this).parent().parent().parent().parent();
        const
            id = tr.data("id"),
            name = tr.data("name");

        $("#option-form").attr("action", `{{ route('administrator.usabilities.index') }}/${id}`);
        $("#option-method").val('PUT');
        $("#option-title").html("Edit Tipe Ulos");

        $("#option-name").val(name);

        $("#option").modal("show");
    });

    $("#option-form").submit(function(e) {
        e.preventDefault();
    }).validate({
        submitHandler: function(form) {
            $("#option-name").prop("readonly", true);

            $("#option-save").prop("disabled", true);
            $("#option-save").html("Tunggu...");

            form.submit();
        }
    });

    $("#table").DataTable({
        responsive: true,
        language: {
            paginate: {
                previous: "‹",
                next: "›"
            }
        },
        processing: true,
        serverSide: true,
        ajax: {
            url: "{{ request()->url() }}",
            headers: {
                "X-CSRF-TOKEN": $('meta[name="csrf-token"]').attr('content')
            }
        },
        columns: [{
            data: "DT_RowIndex",
            orderable: false,
            searchable: false,
            bSortable: false
        }, {
            data: "name"
        }, {
            data: "column_actions",
            orderable: false,
            searchable: false
        }],
        order: [
            [1, "asc"]
        ],
        createdRow: function(row, data, indice) {
            $(row).data("id", data.id);
            $(row).data("name", data.name);

            $('td:eq(0)', row).addClass("align-middle text-center");
            $('td:eq(1)', row).addClass("align-middle");
            $('td:eq(2)', row).addClass("align-middle");
        }
    });
</script>
@endsection